info:
  app:
    name: @project.name@
# Expondo todos os endpoins disponíveis no actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: @project.name@
  cloud:
    stream:
      rabbit:
        bindings:
          person-created-input:
            consumer:
              bindingRoutingKey: person-created-input
              autoBindDlq: true
#              transacted: true
          person-created-protobuf-input:
            consumer:
              bindingRoutingKey: person-created-protobuf-input
              autoBindDlq: true
#              transacted: true
          person-created-output:
            producer:
              routingKeyExpression: '''person-created-protobuf-input'''
#              transacted: true
      bindings:
        person-created-input:
          destination: person-topic
          contentType: application/json
          group: person-created-input
          binder: rabbit
          consumer.max-attempts: 5
        person-created-protobuf-input:
          destination: person-topic
          contentType: application/protobuf
          group: person-created-protobuf-input
          binder: rabbit
          consumer.max-attempts: 5
        person-created-output:
          destination: person-topic
          contentType: application/protobuf
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /