// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonMessage.proto

package br.com.metsys.rabbitprotobuff.pessoa.gateway;

public final class PersonMessage {
  private PersonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface personMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:personMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string nome = 2;</code>
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 2;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    java.util.List<PersonMessage.personContactMessage>
        getContatosList();
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    PersonMessage.personContactMessage getContatos(int index);
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    int getContatosCount();
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    java.util.List<? extends PersonMessage.personContactMessageOrBuilder>
        getContatosOrBuilderList();
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    PersonMessage.personContactMessageOrBuilder getContatosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code personMessage}
   */
  public  static final class personMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:personMessage)
      personMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use personMessage.newBuilder() to construct.
    private personMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private personMessage() {
      nome_ = "";
      email_ = "";
      contatos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new personMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private personMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                contatos_ = new java.util.ArrayList<PersonMessage.personContactMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              contatos_.add(
                  input.readMessage(PersonMessage.personContactMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          contatos_ = java.util.Collections.unmodifiableList(contatos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonMessage.internal_static_personMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonMessage.internal_static_personMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonMessage.personMessage.class, PersonMessage.personMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 2;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTATOS_FIELD_NUMBER = 4;
    private java.util.List<PersonMessage.personContactMessage> contatos_;
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    public java.util.List<PersonMessage.personContactMessage> getContatosList() {
      return contatos_;
    }
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    public java.util.List<? extends PersonMessage.personContactMessageOrBuilder>
        getContatosOrBuilderList() {
      return contatos_;
    }
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    public int getContatosCount() {
      return contatos_.size();
    }
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    public PersonMessage.personContactMessage getContatos(int index) {
      return contatos_.get(index);
    }
    /**
     * <code>repeated .personContactMessage contatos = 4;</code>
     */
    public PersonMessage.personContactMessageOrBuilder getContatosOrBuilder(
        int index) {
      return contatos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < contatos_.size(); i++) {
        output.writeMessage(4, contatos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      for (int i = 0; i < contatos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, contatos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PersonMessage.personMessage)) {
        return super.equals(obj);
      }
      PersonMessage.personMessage other = (PersonMessage.personMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getContatosList()
          .equals(other.getContatosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getContatosCount() > 0) {
        hash = (37 * hash) + CONTATOS_FIELD_NUMBER;
        hash = (53 * hash) + getContatosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PersonMessage.personMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMessage.personMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMessage.personMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMessage.personMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMessage.personMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMessage.personMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMessage.personMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonMessage.personMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonMessage.personMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PersonMessage.personMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonMessage.personMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonMessage.personMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PersonMessage.personMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code personMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:personMessage)
        PersonMessage.personMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMessage.internal_static_personMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMessage.internal_static_personMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMessage.personMessage.class, PersonMessage.personMessage.Builder.class);
      }

      // Construct using br.com.metsys.rabbitprotobuff.pessoa.gateway.PersonMessage.personMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContatosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        nome_ = "";

        email_ = "";

        if (contatosBuilder_ == null) {
          contatos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contatosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonMessage.internal_static_personMessage_descriptor;
      }

      @java.lang.Override
      public PersonMessage.personMessage getDefaultInstanceForType() {
        return PersonMessage.personMessage.getDefaultInstance();
      }

      @java.lang.Override
      public PersonMessage.personMessage build() {
        PersonMessage.personMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PersonMessage.personMessage buildPartial() {
        PersonMessage.personMessage result = new PersonMessage.personMessage(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.nome_ = nome_;
        result.email_ = email_;
        if (contatosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            contatos_ = java.util.Collections.unmodifiableList(contatos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contatos_ = contatos_;
        } else {
          result.contatos_ = contatosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonMessage.personMessage) {
          return mergeFrom((PersonMessage.personMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonMessage.personMessage other) {
        if (other == PersonMessage.personMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (contatosBuilder_ == null) {
          if (!other.contatos_.isEmpty()) {
            if (contatos_.isEmpty()) {
              contatos_ = other.contatos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContatosIsMutable();
              contatos_.addAll(other.contatos_);
            }
            onChanged();
          }
        } else {
          if (!other.contatos_.isEmpty()) {
            if (contatosBuilder_.isEmpty()) {
              contatosBuilder_.dispose();
              contatosBuilder_ = null;
              contatos_ = other.contatos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contatosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContatosFieldBuilder() : null;
            } else {
              contatosBuilder_.addAllMessages(other.contatos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonMessage.personMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonMessage.personMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 2;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<PersonMessage.personContactMessage> contatos_ =
        java.util.Collections.emptyList();
      private void ensureContatosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contatos_ = new java.util.ArrayList<PersonMessage.personContactMessage>(contatos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PersonMessage.personContactMessage, PersonMessage.personContactMessage.Builder, PersonMessage.personContactMessageOrBuilder> contatosBuilder_;

      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public java.util.List<PersonMessage.personContactMessage> getContatosList() {
        if (contatosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contatos_);
        } else {
          return contatosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public int getContatosCount() {
        if (contatosBuilder_ == null) {
          return contatos_.size();
        } else {
          return contatosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public PersonMessage.personContactMessage getContatos(int index) {
        if (contatosBuilder_ == null) {
          return contatos_.get(index);
        } else {
          return contatosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder setContatos(
          int index, PersonMessage.personContactMessage value) {
        if (contatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContatosIsMutable();
          contatos_.set(index, value);
          onChanged();
        } else {
          contatosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder setContatos(
          int index, PersonMessage.personContactMessage.Builder builderForValue) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.set(index, builderForValue.build());
          onChanged();
        } else {
          contatosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder addContatos(PersonMessage.personContactMessage value) {
        if (contatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContatosIsMutable();
          contatos_.add(value);
          onChanged();
        } else {
          contatosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder addContatos(
          int index, PersonMessage.personContactMessage value) {
        if (contatosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContatosIsMutable();
          contatos_.add(index, value);
          onChanged();
        } else {
          contatosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder addContatos(
          PersonMessage.personContactMessage.Builder builderForValue) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.add(builderForValue.build());
          onChanged();
        } else {
          contatosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder addContatos(
          int index, PersonMessage.personContactMessage.Builder builderForValue) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.add(index, builderForValue.build());
          onChanged();
        } else {
          contatosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder addAllContatos(
          java.lang.Iterable<? extends PersonMessage.personContactMessage> values) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contatos_);
          onChanged();
        } else {
          contatosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder clearContatos() {
        if (contatosBuilder_ == null) {
          contatos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contatosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public Builder removeContatos(int index) {
        if (contatosBuilder_ == null) {
          ensureContatosIsMutable();
          contatos_.remove(index);
          onChanged();
        } else {
          contatosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public PersonMessage.personContactMessage.Builder getContatosBuilder(
          int index) {
        return getContatosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public PersonMessage.personContactMessageOrBuilder getContatosOrBuilder(
          int index) {
        if (contatosBuilder_ == null) {
          return contatos_.get(index);  } else {
          return contatosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public java.util.List<? extends PersonMessage.personContactMessageOrBuilder>
           getContatosOrBuilderList() {
        if (contatosBuilder_ != null) {
          return contatosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contatos_);
        }
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public PersonMessage.personContactMessage.Builder addContatosBuilder() {
        return getContatosFieldBuilder().addBuilder(
            PersonMessage.personContactMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public PersonMessage.personContactMessage.Builder addContatosBuilder(
          int index) {
        return getContatosFieldBuilder().addBuilder(
            index, PersonMessage.personContactMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .personContactMessage contatos = 4;</code>
       */
      public java.util.List<PersonMessage.personContactMessage.Builder>
           getContatosBuilderList() {
        return getContatosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PersonMessage.personContactMessage, PersonMessage.personContactMessage.Builder, PersonMessage.personContactMessageOrBuilder>
          getContatosFieldBuilder() {
        if (contatosBuilder_ == null) {
          contatosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PersonMessage.personContactMessage, PersonMessage.personContactMessage.Builder, PersonMessage.personContactMessageOrBuilder>(
                  contatos_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          contatos_ = null;
        }
        return contatosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:personMessage)
    }

    // @@protoc_insertion_point(class_scope:personMessage)
    private static final PersonMessage.personMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PersonMessage.personMessage();
    }

    public static PersonMessage.personMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<personMessage>
        PARSER = new com.google.protobuf.AbstractParser<personMessage>() {
      @java.lang.Override
      public personMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new personMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<personMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<personMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PersonMessage.personMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface personContactMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:personContactMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string ddd = 5;</code>
     */
    java.util.List<java.lang.String>
        getDddList();
    /**
     * <code>repeated string ddd = 5;</code>
     */
    int getDddCount();
    /**
     * <code>repeated string ddd = 5;</code>
     */
    java.lang.String getDdd(int index);
    /**
     * <code>repeated string ddd = 5;</code>
     */
    com.google.protobuf.ByteString
        getDddBytes(int index);

    /**
     * <code>repeated string numero = 6;</code>
     */
    java.util.List<java.lang.String>
        getNumeroList();
    /**
     * <code>repeated string numero = 6;</code>
     */
    int getNumeroCount();
    /**
     * <code>repeated string numero = 6;</code>
     */
    java.lang.String getNumero(int index);
    /**
     * <code>repeated string numero = 6;</code>
     */
    com.google.protobuf.ByteString
        getNumeroBytes(int index);

    /**
     * <code>repeated bool principal = 7;</code>
     */
    java.util.List<java.lang.Boolean> getPrincipalList();
    /**
     * <code>repeated bool principal = 7;</code>
     */
    int getPrincipalCount();
    /**
     * <code>repeated bool principal = 7;</code>
     */
    boolean getPrincipal(int index);
  }
  /**
   * Protobuf type {@code personContactMessage}
   */
  public  static final class personContactMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:personContactMessage)
      personContactMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use personContactMessage.newBuilder() to construct.
    private personContactMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private personContactMessage() {
      ddd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      numero_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      principal_ = emptyBooleanList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new personContactMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private personContactMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ddd_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              ddd_.add(s);
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                numero_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              numero_.add(s);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                principal_ = newBooleanList();
                mutable_bitField0_ |= 0x00000004;
              }
              principal_.addBoolean(input.readBool());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                principal_ = newBooleanList();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                principal_.addBoolean(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ddd_ = ddd_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          numero_ = numero_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          principal_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonMessage.internal_static_personContactMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonMessage.internal_static_personContactMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonMessage.personContactMessage.class, PersonMessage.personContactMessage.Builder.class);
    }

    public static final int DDD_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList ddd_;
    /**
     * <code>repeated string ddd = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDddList() {
      return ddd_;
    }
    /**
     * <code>repeated string ddd = 5;</code>
     */
    public int getDddCount() {
      return ddd_.size();
    }
    /**
     * <code>repeated string ddd = 5;</code>
     */
    public java.lang.String getDdd(int index) {
      return ddd_.get(index);
    }
    /**
     * <code>repeated string ddd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDddBytes(int index) {
      return ddd_.getByteString(index);
    }

    public static final int NUMERO_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList numero_;
    /**
     * <code>repeated string numero = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNumeroList() {
      return numero_;
    }
    /**
     * <code>repeated string numero = 6;</code>
     */
    public int getNumeroCount() {
      return numero_.size();
    }
    /**
     * <code>repeated string numero = 6;</code>
     */
    public java.lang.String getNumero(int index) {
      return numero_.get(index);
    }
    /**
     * <code>repeated string numero = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNumeroBytes(int index) {
      return numero_.getByteString(index);
    }

    public static final int PRINCIPAL_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.BooleanList principal_;
    /**
     * <code>repeated bool principal = 7;</code>
     */
    public java.util.List<java.lang.Boolean>
        getPrincipalList() {
      return principal_;
    }
    /**
     * <code>repeated bool principal = 7;</code>
     */
    public int getPrincipalCount() {
      return principal_.size();
    }
    /**
     * <code>repeated bool principal = 7;</code>
     */
    public boolean getPrincipal(int index) {
      return principal_.getBoolean(index);
    }
    private int principalMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ddd_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ddd_.getRaw(i));
      }
      for (int i = 0; i < numero_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, numero_.getRaw(i));
      }
      if (getPrincipalList().size() > 0) {
        output.writeUInt32NoTag(58);
        output.writeUInt32NoTag(principalMemoizedSerializedSize);
      }
      for (int i = 0; i < principal_.size(); i++) {
        output.writeBoolNoTag(principal_.getBoolean(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ddd_.size(); i++) {
          dataSize += computeStringSizeNoTag(ddd_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDddList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < numero_.size(); i++) {
          dataSize += computeStringSizeNoTag(numero_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNumeroList().size();
      }
      {
        int dataSize = 0;
        dataSize = 1 * getPrincipalList().size();
        size += dataSize;
        if (!getPrincipalList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        principalMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PersonMessage.personContactMessage)) {
        return super.equals(obj);
      }
      PersonMessage.personContactMessage other = (PersonMessage.personContactMessage) obj;

      if (!getDddList()
          .equals(other.getDddList())) return false;
      if (!getNumeroList()
          .equals(other.getNumeroList())) return false;
      if (!getPrincipalList()
          .equals(other.getPrincipalList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDddCount() > 0) {
        hash = (37 * hash) + DDD_FIELD_NUMBER;
        hash = (53 * hash) + getDddList().hashCode();
      }
      if (getNumeroCount() > 0) {
        hash = (37 * hash) + NUMERO_FIELD_NUMBER;
        hash = (53 * hash) + getNumeroList().hashCode();
      }
      if (getPrincipalCount() > 0) {
        hash = (37 * hash) + PRINCIPAL_FIELD_NUMBER;
        hash = (53 * hash) + getPrincipalList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PersonMessage.personContactMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMessage.personContactMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMessage.personContactMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMessage.personContactMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMessage.personContactMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonMessage.personContactMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonMessage.personContactMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonMessage.personContactMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonMessage.personContactMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PersonMessage.personContactMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PersonMessage.personContactMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PersonMessage.personContactMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PersonMessage.personContactMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code personContactMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:personContactMessage)
        PersonMessage.personContactMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonMessage.internal_static_personContactMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonMessage.internal_static_personContactMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonMessage.personContactMessage.class, PersonMessage.personContactMessage.Builder.class);
      }

      // Construct using br.com.metsys.rabbitprotobuff.pessoa.gateway.PersonMessage.personContactMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ddd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        numero_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        principal_ = emptyBooleanList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonMessage.internal_static_personContactMessage_descriptor;
      }

      @java.lang.Override
      public PersonMessage.personContactMessage getDefaultInstanceForType() {
        return PersonMessage.personContactMessage.getDefaultInstance();
      }

      @java.lang.Override
      public PersonMessage.personContactMessage build() {
        PersonMessage.personContactMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PersonMessage.personContactMessage buildPartial() {
        PersonMessage.personContactMessage result = new PersonMessage.personContactMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          ddd_ = ddd_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ddd_ = ddd_;
        if (((bitField0_ & 0x00000002) != 0)) {
          numero_ = numero_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.numero_ = numero_;
        if (((bitField0_ & 0x00000004) != 0)) {
          principal_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.principal_ = principal_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonMessage.personContactMessage) {
          return mergeFrom((PersonMessage.personContactMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonMessage.personContactMessage other) {
        if (other == PersonMessage.personContactMessage.getDefaultInstance()) return this;
        if (!other.ddd_.isEmpty()) {
          if (ddd_.isEmpty()) {
            ddd_ = other.ddd_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDddIsMutable();
            ddd_.addAll(other.ddd_);
          }
          onChanged();
        }
        if (!other.numero_.isEmpty()) {
          if (numero_.isEmpty()) {
            numero_ = other.numero_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNumeroIsMutable();
            numero_.addAll(other.numero_);
          }
          onChanged();
        }
        if (!other.principal_.isEmpty()) {
          if (principal_.isEmpty()) {
            principal_ = other.principal_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePrincipalIsMutable();
            principal_.addAll(other.principal_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonMessage.personContactMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonMessage.personContactMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList ddd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDddIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ddd_ = new com.google.protobuf.LazyStringArrayList(ddd_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDddList() {
        return ddd_.getUnmodifiableView();
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public int getDddCount() {
        return ddd_.size();
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public java.lang.String getDdd(int index) {
        return ddd_.get(index);
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDddBytes(int index) {
        return ddd_.getByteString(index);
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public Builder setDdd(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDddIsMutable();
        ddd_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public Builder addDdd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDddIsMutable();
        ddd_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public Builder addAllDdd(
          java.lang.Iterable<java.lang.String> values) {
        ensureDddIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ddd_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public Builder clearDdd() {
        ddd_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ddd = 5;</code>
       */
      public Builder addDddBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDddIsMutable();
        ddd_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList numero_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNumeroIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          numero_ = new com.google.protobuf.LazyStringArrayList(numero_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNumeroList() {
        return numero_.getUnmodifiableView();
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public int getNumeroCount() {
        return numero_.size();
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public java.lang.String getNumero(int index) {
        return numero_.get(index);
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNumeroBytes(int index) {
        return numero_.getByteString(index);
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public Builder setNumero(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNumeroIsMutable();
        numero_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public Builder addNumero(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNumeroIsMutable();
        numero_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public Builder addAllNumero(
          java.lang.Iterable<java.lang.String> values) {
        ensureNumeroIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, numero_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public Builder clearNumero() {
        numero_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string numero = 6;</code>
       */
      public Builder addNumeroBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureNumeroIsMutable();
        numero_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.BooleanList principal_ = emptyBooleanList();
      private void ensurePrincipalIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          principal_ = mutableCopy(principal_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public java.util.List<java.lang.Boolean>
          getPrincipalList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(principal_) : principal_;
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public int getPrincipalCount() {
        return principal_.size();
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public boolean getPrincipal(int index) {
        return principal_.getBoolean(index);
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public Builder setPrincipal(
          int index, boolean value) {
        ensurePrincipalIsMutable();
        principal_.setBoolean(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public Builder addPrincipal(boolean value) {
        ensurePrincipalIsMutable();
        principal_.addBoolean(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public Builder addAllPrincipal(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensurePrincipalIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, principal_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool principal = 7;</code>
       */
      public Builder clearPrincipal() {
        principal_ = emptyBooleanList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:personContactMessage)
    }

    // @@protoc_insertion_point(class_scope:personContactMessage)
    private static final PersonMessage.personContactMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PersonMessage.personContactMessage();
    }

    public static PersonMessage.personContactMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<personContactMessage>
        PARSER = new com.google.protobuf.AbstractParser<personContactMessage>() {
      @java.lang.Override
      public personContactMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new personContactMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<personContactMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<personContactMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PersonMessage.personContactMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_personMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_personMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_personContactMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_personContactMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PersonMessage.proto\"a\n\rpersonMessage\022\n" +
      "\n\002id\030\001 \001(\r\022\014\n\004nome\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022" +
      "\'\n\010contatos\030\004 \003(\0132\025.personContactMessage" +
      "\"F\n\024personContactMessage\022\013\n\003ddd\030\005 \003(\t\022\016\n" +
      "\006numero\030\006 \003(\t\022\021\n\tprincipal\030\007 \003(\010B!\n\037br.c" +
      "om.metsys.rabbitprotobuff.pessoab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_personMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_personMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_personMessage_descriptor,
        new java.lang.String[] { "Id", "Nome", "Email", "Contatos", });
    internal_static_personContactMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_personContactMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_personContactMessage_descriptor,
        new java.lang.String[] { "Ddd", "Numero", "Principal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
